# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/Gait_Analysis',
                'doc_host': 'https://Defense-Circuits-Lab.github.io',
                'git_url': 'https://github.com/Defense-Circuits-Lab/Gait_Analysis',
                'lib_path': 'gait_analysis'},
  'syms': {'gait_analysis.core': {'gait_analysis.core.foo': ('core.html#foo', 'gait_analysis/core.py')}}}